Add build container step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,6 +11,32 @@ on:
   workflow_dispatch:
 
 jobs:
+  lint-eslint:
+    name: ESLint
+    runs-on: ubuntu-latest
+    steps:
+      - name: ⤵️ Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+      - name: 🏗 Set up Node.js
+        uses: actions/setup-node@v2.1.4
+        with:
+          node-version: 14.x
+      - name: ⤵️ Get yarn cache path
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: ⤵️ Fetch Yarn cache
+        uses: actions/cache@v2.1.4
+        with:
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+      - name: ⤵️ Install dependencies
+        run: yarn install
+        env:
+          CI: true
+      - name: 🚀 Run ESLint
+        run: yarn eslint
   lint-hadolint:
     name: Hadolint
     runs-on: ubuntu-latest
@@ -66,6 +92,18 @@ jobs:
           check-modified-files-only: no
           base-branch: master
           file-extension: .md
+  lint-prettier:
+    name: Prettier
+    runs-on: ubuntu-latest
+    steps:
+      - name: ⤵️ Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+      - name: 🚀 Run Prettier
+        uses: creyD/prettier_action@v3.3
+        with:
+          prettier_options: --write **/*.{js,json,md,ts,tsx,yaml}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   lint-shellcheck:
     name: ShellCheck
     runs-on: ubuntu-latest
@@ -82,7 +120,7 @@ jobs:
         with:
           ignore: .devcontainer .vscode .yarn
           check_together: yes
-  lint-yaml:
+  lint-yamllint:
     name: YAMLLint
     runs-on: ubuntu-latest
     steps:
@@ -95,51 +133,13 @@ jobs:
           config_file: .yamllint.yml
           format: colored
           strict: false
-  lint-eslint:
-    name: ESLint
-    runs-on: ubuntu-latest
-    steps:
-      - name: ⤵️ Check out code from GitHub
-        uses: actions/checkout@v2.3.4
-      - name: ⤵️ Set up Node.js
-        uses: actions/setup-node@v2.1.4
-        with:
-          node-version: 14.x
-      - name: ⤵️ Get yarn cache path
-        id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-      - name: ⤵️ Fetch Yarn cache
-        uses: actions/cache@v2.1.4
-        with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
-      - name: ⤵️ Install dependencies
-        run: yarn install
-        env:
-          CI: true
-      - name: 🚀 Run ESLint
-        run: yarn eslint
-  lint-prettier:
-    name: Prettier
-    runs-on: ubuntu-latest
-    steps:
-      - name: ⤵️ Check out code from GitHub
-        uses: actions/checkout@v2.3.4
-      - name: 🚀 Run Prettier
-        uses: creyD/prettier_action@v3.3
-        with:
-          prettier_options: --write **/*.{js,json,md,ts,tsx,yaml}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  test:
+  tests:
     name: Tests
     runs-on: ubuntu-latest
     steps:
       - name: ⤵️ Check out code from GitHub
         uses: actions/checkout@v2.3.4
-      - name: ⤵️ Set up Node.js
+      - name: 🏗 Set up Node.js
         uses: actions/setup-node@v2.1.4
         with:
           node-version: 14.x
@@ -167,13 +167,13 @@ jobs:
         env:
           CI: true
         working-directory: frontend
-  build:
-    name: Build
+  build-app:
+    name: Build Application
     runs-on: ubuntu-latest
     steps:
       - name: ⤵️ Check out code from GitHub
         uses: actions/checkout@v2.3.4
-      - name: ⤵️ Set up Node.js
+      - name: 🏗 Set up Node.js
         uses: actions/setup-node@v2.1.4
         with:
           node-version: 14.x
@@ -214,3 +214,80 @@ jobs:
         with:
           name: frontend-build
           path: frontend/build/
+  build-container:
+    name: Build Container - ${{ matrix.architecture }}
+    needs:
+      - lint-eslint
+      - lint-hadolint
+      - lint-json
+      - lint-markdown
+      - lint-markdown-links
+      - lint-prettier
+      - lint-shellcheck
+      - lint-yamllint
+      - tests
+      - build-app
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        architecture:
+          - aarch64
+          - amd64
+          - armhf
+          - armv7
+          - i386
+    steps:
+      - name: ⤵️ Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+      - name: 🏗 Set up build cache
+        id: cache
+        uses: actions/cache@v2.1.4
+        with:
+          path: /tmp/.docker-cache
+          key: docker-${{ github.ref }}-${{ matrix.architecture }}-${{ github.sha }}
+          restore-keys: |
+            docker-${{ github.ref }}-${{ matrix.architecture }}
+      - name: 🏗 Set up QEMU
+        uses: docker/setup-qemu-action@v1.0.1
+      - name: 🏗 Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1.1.1
+      - name: ℹ️ Compose build flags
+        id: flags
+        run: |
+          echo "::set-output name=date::$(date +"%Y-%m-%dT%H:%M:%SZ")"
+          from=$(jq --raw-output ".build_from.${{ matrix.architecture }}" "build.json")
+          echo "::set-output name=from::${from}"
+          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
+            echo "::set-output name=platform::linux/amd64"
+          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
+            echo "::set-output name=platform::linux/386"
+          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
+            echo "::set-output name=platform::linux/arm/v6"
+          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
+            echo "::set-output name=platform::linux/arm/v7"
+          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
+            echo "::set-output name=platform::linux/arm64/v8"
+          else
+            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
+            exit 1
+          fi
+      - name: 🚀 Build
+        uses: docker/build-push-action@v2.3.0
+        with:
+          push: false
+          context: .
+          file: Dockerfile
+          cache-from: |
+            type=local,src=/tmp/.docker-cache
+            ghcr.io/timmo001/home-panel/${{ matrix.architecture }}:edge
+          cache-to: type=local,mode=max,dest=/tmp/.docker-cache
+          platforms: ${{ steps.flags.outputs.platform }}
+          build-args: |
+            BUILD_ARCH=${{ matrix.architecture }}
+            BUILD_DATE=${{ steps.flags.outputs.date }}
+            BUILD_DESCRIPTION=$(jq --raw-output ".description" "build.json")
+            BUILD_FROM=${{ steps.flags.outputs.from }}
+            BUILD_NAME=$(jq --raw-output ".description" "build.json")
+            BUILD_REF=${{ github.sha }}
+            BUILD_REPOSITORY=${{ github.repository }}
+            BUILD_VERSION=edge
